export default {
	modules: ["DisplaySize", "Toolbar", "Resize"],
	overlayStyles: {
		position: "absolute",
		boxSizing: "border-box",
		border: "1px dashed #444",
	},
	handleStyles: {
		position: "absolute",
		height: "12px",
		width: "12px",
		backgroundColor: "white",
		border: "1px solid #777",
		boxSizing: "border-box",
		opacity: "0.80",
	},
	displayStyles: {
		position: "absolute",
		font: "12px/1.0 Arial, Helvetica, sans-serif",
		padding: "4px 8px",
		textAlign: "center",
		backgroundColor: "white",
		color: "#333",
		border: "1px solid #777",
		boxSizing: "border-box",
		opacity: "0.80",
		cursor: "default",
	},
	toolbarStyles: {
		position: "absolute",
		top: "-12px",
		display: "flex",
		gap: "8px",
		justifyContent: "center",
		right: "0",
		left: "0",
		height: "0",
		minWidth: "100px",
		textAlign: "center",
		color: "#333",
		boxSizing: "border-box",
		cursor: "default",
	},
	toolbarContainersStyles: {
		display: "flex",
		background: "white",
		height: "30px",
		justifyContent: "center",
		border: "1px solid #B0BEC5",
		borderRadius: "4px",
	},
	toolbarAlignmentsButtonStyles: {
		display: "flex",
		width: "24px",
		height: "100%",
		background: "white",
		verticalAlign: "middle",
		borderRight: "1px solid #B0BEC5",
	},
	toolbarButtonStyles: {
		display: "inline-block",
		padding: "7px",
		background: "white",
		verticalAlign: "middle",
		borderRight: "1px solid #B0BEC5",
	},
	svgStyles: {
		height: "14px",
	},
	toolbarAlignmentsButtonSvgStyles: {
		fill: "#B0BEC5",
		stroke: "#B0BEC5",
		strokeWidth: "2",
	},
};
